# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance: 
  theme_day: minimal
  theme_night: minimal
  font: minimal 
  font_size: M

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'philip_khor'
  analytics: 
    google_analytics: 'G-98QCCJTRLM'
    google_tag_manager: 'G-98QCCJTRLM'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header: 
  navbar: 
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer: 
  copyright: 
    notice: 'This work is licensed under {license}'
    license:
      # enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

features: 
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark
    extra_languages:
      - r   
  math: 
    enable: true
  privacy_pack: 
    enable: true
  repository:
    url: 'https://github.com/philip-khor/blog-refresh'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'disqus'
    disqus:
      shortname: 'philips-curve'
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15


extensions:
  cms:
    branch: master
    local_backend: false
  isotope: false
  academicons: 
    enable: true
