# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance: 
  theme: Minimal
  day_night: true
  font: 'Minimal'
  font_size: M

# SEO
seo: 
  site_type: Person
  local_business_type: ''
  org_name: ''
  description: ''
  twitter: ''

# Contact (edit or remove options as required)

email: pk.qa@outlook.com

contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/philip_khor'

# Site header

header: 
  navbar: 
    enable: true
    
footer: 
  copyright: 
    notice: 'This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false


# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us


# Site features
features: 
  syntax_highlighter:
    enable: true
    extra_languages:
      - r   
  math: 
    enable: true
  diagram: 
    enable: true
  privacy_pack: 
    enable: true
  edit_page:
    repo_url: 'https://github.com/philip-khor/blog-refresh'
    content_dir: ''
    repo_branch: master
    editable:
      page: false
      post: true
  show_related:
    book: false
    page: false
    post: true
    project: true
    publication: true
    talk: true
  reading_time: true
  section_pager: false
  docs_section_pager: true
  sharing: true
  
  abstract_length: 135
  plugins_js: []
  avatar:
    gravatar: false
    shape: circle
  publications:
    date_format: January 2006
    citation_style: apa
  projects:
    post_view: 2
    publication_view: 2
    talk_view: 2
  breadcrumb:
    page_types:
      book: true
  comments:
    provider: 'disqus'
    commentable:
      post: true
      book: false
      project: false
      publication: false
      event: false
    disqus:
      shortname: 'philips-curve'
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 0
    api_key: ''
    zoom: 15
  marketing:
    analytics: 
      google_analytics: 'G-98QCCJTRLM'
      google_tag_manager: 'G-98QCCJTRLM'
      # google_site_verification: ''
      # baidu_site_verification: ''
      baidu_tongji: ''
  cms:
    branch: master
    publish_mode: editorial_workflow
    local_backend: false
  icon:
    pack:
      ai: false